Ví dụ 1 (ANN đơn giản)

In [22]:
import numpy as np
X=np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
y=np.array([[0,1,1,0]]).T
w = np.random.random((3,1))
for i in range(100000):
    z=np.dot(X,w)
    O=1/(1+np.exp(-z))
    w = w - np.dot(X.T, (O- y) * O * (1 - O))
print('finished')

finished


In [23]:
w

array([[12.00867681],
       [-0.2044436 ],
       [-5.80025121]])

In [24]:
O

array([[0.00301768],
       [0.99753717],
       [0.99799163],
       [0.00246108]])

In [2]:
z=np.dot(X[0],w)
O=1/(1+np.exp(-z))
print(O)

[0.00966701]


In [3]:
(O-y)*O*(1-O)

array([[ 9.25477695e-05],
       [-9.48101525e-03],
       [-9.48101525e-03],
       [ 9.25477695e-05]])

In [4]:
X

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [5]:
for i in range(4):
    z=np.dot(X[i],w)
    O=1/(1+np.exp(-z))
    print(O)

[0.00966701]
[0.99211832]
[0.99359138]
[0.00786292]


In [25]:
import numpy as np
X=np.array([[0,0],[1,1],[1,0],[0,1]])
y=np.array([[0,0,1,1,]]).T
w = np.random.random((2,1))
for i in range(1000000):
    z=np.dot(X,w)
    O=1/(1+np.exp(-z))
    w = w - np.dot(X.T, (O- y) * O * (1 - O))
print('finished')


finished


In [27]:
O

array([[0.5],
       [0.5],
       [0.5],
       [0.5]])

In [20]:
for i in range(4):
    z=np.dot(X[i],w)
    O=1/(1+np.exp(-z))
    print(O)

[0.5]
[0.5]
[0.5]
[0.5]
