Ma trận nghịch đảo và ma trận giả nghịch đảo

In [15]:
import numpy as np
a=np.array([[1,2,3],[1,3,4],[1,3,5]])

In [9]:
a.shape

(2, 2)

In [16]:
b= np.linalg.inv(a) 

In [19]:
print(a)
print(b)
c=np.dot(a,b)
print(c)

[[1 2 3]
 [1 3 4]
 [1 3 5]]
[[ 3. -1. -1.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
print(np.linalg.pinv(a))

[[ 3.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  2.00000000e+00 -1.00000000e+00]
 [-3.13134861e-16 -1.00000000e+00  1.00000000e+00]]


In [23]:
a

array([[1, 2, 3],
       [1, 3, 4],
       [1, 3, 5]])

In [24]:
print(np.linalg.det(a))

1.0


In [27]:
m=np.array([[1,2,3],[1,3,4]])

In [28]:
n= np.linalg.pinv(m)

In [29]:
print(n)

[[ 2.33333333 -1.66666667]
 [-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


In [30]:
p=np.dot(m,n)